### ISSUE TITLE
Observaciones

### ISSUE THREAD

**Issue by Gorusuke** [andresovalle8/Citas_Pet#1]
No hay nada en este repositorio aparte del readme!
Por lo tanto este ejercicio no califica!

**Comment by andresovalle8** [comment]
Hola profe todo estaba en la rama master "https://github.com/andresovalle8/Citas_Pet"

**Comment by Gorusuke** [comment]
Gracias por decirme, no habia visto que tenias mas de 1 rama.
Buena presentacion del ejercicio. La UI me parece que va muy acorde con lo requerido, pero tiene un par de problemas a mi parecer.

- En el campo de la edad estaria bueno que solo aceptara numeros. Porque por ejemplo puedo escribir **_letras_**.
- En el dia de la cita debes de poner un calendario porque si no es muy facil poner por ejemplo **_letras_** y eso no es lo que queremos.

Por otro lado tambien vi que utilizastes classes (cosa que ya no es muy comun en los componentes). No es que este mal, porque la aplicacion funciona pero mejor si lo haces con las tecnologias que se utilizan actualmente (Hooks).
Muy bien las validaciones de los campos, me gusto como esta hecho. Aparte de eso, nada mas que agregar, Felicitaciones!!
Sigue asi! ❤
